{{- if ( index .Values "template-controller" "objectTemplate" "enabled" ) }}
apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: {{ include "digitalhub.fullname" . }}-common-creds-transformer
spec:
  serviceAccountName: secret-transformer
  prune: true
  matrix:
    - name: postgressecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: digitalhub-owner-user.database-postgres-cluster.credentials.postgresql.acid.zalan.do
    - name: miniosecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: digitalhub-minio-creds
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "digitalhub-common-creds"
      stringData:
        POSTGRES_USER: "{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}"
        POSTGRES_PASSWORD: "{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}"
        AWS_ACCESS_KEY_ID: "{{ "{{" }} matrix.miniosecret.data.digitalhubUser | b64decode {{ "}}" }}"
        AWS_SECRET_ACCESS_KEY: "{{ "{{" }} matrix.miniosecret.data.digitalhubPassword | b64decode {{ "}}" }}"
        JUPYTERLAB_S3_ACCESS_KEY_ID: "{{ "{{" }} matrix.miniosecret.data.digitalhubUser | b64decode {{ "}}" }}"
        JUPYTERLAB_S3_SECRET_ACCESS_KEY: "{{ "{{" }} matrix.miniosecret.data.digitalhubPassword | b64decode {{ "}}" }}"
        POSTGRES_URL: "postgresql://{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}:{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}@database-postgres-cluster:5432/digitalhub"
{{- end }}
