{{- $v := tpl (.Files.Get "confs/bootstrap.yaml") . }}
{{- if not .Values.bootstrapCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: aac-bootstrap-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  bootstrap.yaml: {{ $v | b64enc }}
{{- end }}
{{- if not .Values.appCreds.existingSecret -}}
{{- if .Values.bootstrap }}
{{- range $realm := ($v | fromYaml).realms }}
{{- if $realm.clientApps  }}
{{- range $clientApp := $realm.clientApps }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aac-{{ $realm.name | replace " " "-"}}-{{ $clientApp.name | replace " " "-"}}-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    {{- with $.Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.secrets.reflector.enabled }}
    "reflector.v1.k8s.emberstack.com/reflection-allowed": "true"
    "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": {{ $realm.name | quote }}  # Control destination namespaces
    "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true" # Auto create reflection for matching namespaces
    "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": {{ $realm.name | quote }} # Control auto-reflection namespaces
    {{- end }}
type: Opaque
data:
  clientid: {{ $clientApp.clientId | b64enc }}
  clientsecret: {{ $clientApp.configuration.clientSecret  | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if not (.Values.mailCreds.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aac-mail-secret
type: Opaque
data:
  jdbc-user: {{ .Values.mailSecret.user | b64enc }}
  jdbc-password: {{ .Values.mailSecret.password | b64enc }}
{{- end }}
---
{{- if not .Values.adminExistingCreds.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: aac-admin-secret
type: Opaque
data:
  username: {{ .Values.adminCreds.username | b64enc }}
  password: {{ .Values.adminCreds.password | b64enc }}
{{- end }}
---
{{- if .Values.jdbcH2creds.user }}
apiVersion: v1
kind: Secret
metadata:
  name: aac-h2-creds
type: Opaque
data:
  user: {{ .Values.jdbcH2creds.user | b64enc }}
  password: {{ .Values.jdbcH2creds.password | b64enc }}
{{- end }}
